azure:
  storage:
    account-name: cs11003200080ded6e1
    account-key: hnIAgfyPj4084FZN/qSCHT3v3w8mAyUaGn+aP/hZAs1kf+ecNPiEH/HE4k7kcm7UI6agb/S8/IXD7S3tctKQgw==
    container-name: lokanovels
    connection-string: hnIAgfyPj4084FZN/qSCHT3v3w8mAyUaGn+aP/hZAs1kf+ecNPiEH/HE4k7kcm7UI6agb/S8/IXD7S3tctKQgw==

# blob.connection-string=hnIAgfyPj4084FZN/qSCHT3v3w8mAyUaGn+aP/hZAs1kf+ecNPiEH/HE4k7kcm7UI6agb/S8/IXD7S3tctKQgw==
# blob.container-name=lokanovels

# spring.cloud.azure.credential-file-path=my.azureauth
# spring.cloud.azure.resource-group=DefaultResourceGroup-CUS
# spring.cloud.azure.region=southeastasia
# spring.cloud.azure.storage.account=cs11003200080ded6e1
# blob=https://cs11003200080ded6e1.blob.core.windows.net/lokanovels