# Nomor port
server:
  port: 8081
  servlet:
    session:
      timeout: 1D

spring:
  profiles:
    active: prod

#Login nama pengguna dan kata sandi
admin:
  username: admin
  password: admin

#Jumlah utas diperbarui secara otomatis oleh perayap
# Disarankan untuk menyetelnya ke 1 jika tidak ada banyak novel atau saat perayap masuk buku baru sedang berjalan
# Saat jumlah novel meningkat, itu dapat meningkat secara bertahap, tetapi disarankan untuk tidak melebihi jumlah utas CPU
crawl:
  update:
    thread: 1





