spring:
  profiles:
    include: [common]
  main:
    allow-bean-definition-overriding: true
  #Redis IP Server
  redis:
    host: 127.0.0.1
    #Redis port koneksi server
    port: 6379
    #Redis kata sandi koneksi server
    password: iamalone0
    jedis:
      pool:
        #Jumlah maksimum koneksi di kumpulan koneksi (gunakan nilai negatif untuk menunjukkan bahwa tidak ada batasan)
        max-active: 8
        #Waktu tunggu pemblokiran maksimum dari kumpulan koneksi (gunakan nilai negatif untuk menunjukkan bahwa tidak ada batasan)
        max-wait: 1
        #Waktu tunggu pemblokiran maksimum dari kumpulan koneksi (gunakan nilai negatif untuk menunjukkan bahwa tidak ada batasan)
        max-idle: 8
        #Koneksi idle terkecil di kumpulan koneksi
        min-idle: 0
    #Waktu koneksi habis (milidetik)
    timeout: 30000
  datasource:
    url: jdbc:mysql://lokanovels.mysql.database.azure.com:3306/lokanovels?useSSL=true&requireSSL=false&serverTimezone=UTC
    username: momoy369@lokanovels
    password: Iamalone0
    driver-class-name: com.mysql.cj.jdbc.Driver


####使用shardingJdbc时，
####所有的jdbcType都不能是LONGVARCHAR,否则会导致java.io.NotSerializableException: java.io.StringReader错误
##### 应该替换所有的 LONGVARCHAR 类型为VARCHAR

sharding:
  jdbc:
    datasource:
      names: ds0 #,ds1
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://lokanovels.mysql.database.azure.com:3306/lokanovels?useSSL=true&requireSSL=false&serverTimezone=UTC
        username: momoy369@lokanovels
        password: Iamalone0
    #      ds1:
    #        type: com.alibaba.druid.pool.DruidDataSource
    #        driver-class-name: com.mysql.jdbc.Driver
    #        url: jdbc:mysql://localhost:3306/novel_plus2
    #        username: root
    #        password: test123456
    config:
      sharding:
        props:
          sql.show: true
        tables:
          book_content:  #book_content tabel
            key-generator-column-name: id  #Kunci utama
            actual-data-nodes: ds${0}.book_content${0..9}  #Node data
            #            database-strategy:  #Strategi sub-perpustakaan
            #              inline:
            #                sharding-column: book_id
            #                algorithm-expression: ds${book_id % 10}
            table-strategy:  #Strategi sub-tabel
              inline:
                shardingColumn: index_id
                algorithm-expression: book_content${index_id % 10}






